apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/refresh: hard
  name: demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/odogwuVal/JE.git
    targetRevision: HEAD
    path: cluster1/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
    retry:
      limit: -1